# n.b. IPv6 is not currently supported in Compose File version 3:
# https://docs.docker.com/compose/compose-file/compose-file-v3/#enable_ipv6
version: "2.4"

# Unfortunately, Docker Compose files offer no means of defining variables, so things like the NAT64
# prefix are hard-coded below. The individual Dockerfiles are parameterized, so it should be
# sufficient to change values in this file only. The only exception is bind9-named.conf, which will
# also need to be updated.

# TODO: do we need privileged mode?
# TODO: remove pcap volumes
# TODO: 172.19 -> 172.18
# TODO: dada -> beef

# TODO: make gateway explicit?
networks:
  testnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
        - subnet: fd00:dead:dada::/48

services:
  # TODO: gateway doc
  gateway:
    build:
      context: .
      dockerfile: gateway.dockerfile
      args:
        - MY_IP=172.19.0.10
        - NAT64_IP=172.19.0.20
        - NAT64_DYN_POOL=172.19.0.128/25
    cap_add:
      - NET_ADMIN
    networks:
      testnet:
        ipv4_address: 172.19.0.10
        ipv6_address: fd00:dead:dada::10
    volumes:
      - ./pcaps:/pcaps
  
  nat64:
    build:
      context: .
      dockerfile: nat64.dockerfile
      args:
        - GATEWAY_IP=172.19.0.10
        - DOCKER_GATEWAY_IP=172.19.0.1
        - TAYGA_CONF_DYNAMIC_POOL=172.19.0.128/25
    environment:
      - TAYGA_CONF_IPV4_ADDR=172.19.0.20
      - TAYGA_CONF_PREFIX=2001:db8:64:ff9b::/96
      - TAYGA_CONF_DYNAMIC_POOL=172.19.0.128/25
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    networks:
      testnet:
        ipv4_address: 172.19.0.20
        ipv6_address: fd00:dead:dada::20
    devices:
      - /dev/net/tun
    volumes:
      - ./pcaps:/pcaps

  dns64:
    build:
      context: .
      dockerfile: dns64.dockerfile
      args:
        - NAT64_PREFIX=2001:db8:64:ff9b::/96
        - NAT64_IPV6_ADDR=fd00:dead:dada::20
        - MY_IPV4=172.19.0.30
    # The dns64 container uses itself for DNS.
    dns: fd00:dead:dada::30
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./bind9-named.conf:/etc/bind/named.conf
      - ./pcaps:/pcaps
    networks:
      testnet:
        ipv4_address: 172.19.0.30
        ipv6_address: fd00:dead:dada::30
  
  client:
    build:
      context: .
      dockerfile: client.dockerfile
      args:
        - NAT64_PREFIX=2001:db8:64:ff9b::/96
        - NAT64_IPV6_ADDR=fd00:dead:dada::20
        - MY_IPV4=172.19.0.40
    dns: fd00:dead:dada::30
    # These environment variables are defined for convenience.
    environment:
      - NAT64_PREFIX=2001:db8:64:ff9b::/96
      - NAT64_DYNAMIC_POOL=172.19.0.128/25
      - TEST_SERVER_IPV4=172.19.0.50
    cap_add:
      - NET_ADMIN
    networks:
      testnet:
        ipv4_address: 172.19.0.40
        ipv6_address: fd00:dead:dada::40
    extra_hosts:
      # Add a host mapping for the test server's NAT64'd IPv4 address.
      - "test-server:2001:db8:64:ff9b::ac13:32"
    volumes:
      - ./pcaps:/pcaps

  test-server:
    build:
      context: .
      dockerfile: test-server.dockerfile
    networks:
      testnet:
        ipv4_address: 172.19.0.50
        ipv6_address: fd00:dead:dada::50
    volumes:
      - ./pcaps:/pcaps
    
